=== yangrui110/asunerp/framework/base/dtd/fadp-containers.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="fadp-containers">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="container"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="container">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.container"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.container">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="class" use="required"/>
        <xs:attribute type="xs:string" name="loaders"/>
    </xs:attributeGroup>
    <xs:element name="property">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
                <xs:element minOccurs="0" ref="property-value"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.property"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.property">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="value"/>
    </xs:attributeGroup>
    <xs:element name="property-value" type="any"/>
    <xs:complexType name="any" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== yangrui110/asunerp/bin/production/fadp/fadp-containers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
-->

<fadp-containers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://127.0.0.1:8888/dtds/fadp-containers.xsd">

    <!-- load the fadp component container (always first) -->
    <container name="component-container" loaders="main,rmi,pos,load-data" class="com.hanlin.fadp.base.container.ComponentContainer"/>

    <container name="component-container-test" loaders="test" class="com.hanlin.fadp.base.container.ComponentContainer">
        <property name="fadp.instrumenterClassName" value="com.hanlin.fadp.base.config.CoberturaInstrumenter"/>
        <property name="fadp.instrumenterFile" value="runtime/logs/cobertura-components.dat"/>
    </container>

    <container name="component-container-limited" loaders="limited" class="com.hanlin.fadp.base.container.ComponentContainer">
        <property name="update-classpath" value="false"/>
    </container>

    <container name="component-container" loaders="testlist" class="com.hanlin.fadp.base.container.JustLoadComponentsContainer"/>

</fadp-containers>
